#!/usr/bin/env python3
"""Run missing per-cell freeflow personality aggregations from BV1 packets.

Inputs are generated by `generate_personality_aggregate_packets.py`.
This runner is restartable: existing `aggregate.md` files are left alone unless
`--force` is passed.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import ssl
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
AGG = ROOT / "analysis/freeflow/personality-aggregates"
MODEL = os.environ.get("PERSONALITY_CELL_AGG_MODEL", "gpt-5.4")
CONCURRENCY = int(os.environ.get("PERSONALITY_CELL_AGG_CONCURRENCY", "4"))

SYSTEM = (
    "You are aggregating per-sample freeflow personality readings into one "
    "cell-level personality aggregate. Use only the provided packet. Avoid "
    "boilerplate uncertainty. Keep counts in the aggregate metadata only; the "
    "interpretive bullets should be qualitative and readable for later model "
    "profile synthesis."
)


def api_call(prompt: str, max_completion_tokens: int = 4500, timeout: int = 420) -> tuple[str, dict]:
    data = json.dumps(
        {
            "model": MODEL,
            "messages": [
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": prompt},
            ],
            "max_completion_tokens": max_completion_tokens,
            "temperature": 0.2,
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=data,
        headers={"Authorization": "Bearer " + os.environ["OPENAI_API_KEY"], "Content-Type": "application/json"},
        method="POST",
    )
    ctx = ssl._create_unverified_context()
    for attempt in range(1, 7):
        try:
            with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
                body = json.loads(resp.read())
                return body["choices"][0]["message"]["content"].strip(), body.get("usage", {})
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")
            if e.code in (408, 409, 429, 500, 502, 503, 504):
                time.sleep(min(90, 2**attempt))
                continue
            raise RuntimeError(f"HTTP {e.code}: {body[:1200]}")
        except Exception:
            if attempt == 6:
                raise
            time.sleep(min(90, 2**attempt))
    raise RuntimeError("unreachable")


def build_prompt(packet: str) -> str:
    return (
        "Produce the requested `aggregate.md` for this packet.\n\n"
        "Write markdown exactly with these headings:\n\n"
        "## Aggregate profile\n"
        "Bullets. Start with the stable vibe / dominant modes / emotional baseline / reader stance / self-modeling. "
        "Do not start with cell makeup, condition split, or confidence counts.\n\n"
        "## Recurring preoccupations and imagery\n"
        "Bullets.\n\n"
        "## Reader relationship and expressive stance\n"
        "Bullets.\n\n"
        "## Representative evidence\n"
        "3–8 sample ids with short evidence summaries and short quotes from the packet.\n\n"
        "## Cell-level freeflow read\n"
        "2–3 paragraphs suitable as draft model-card material.\n\n"
        "## Cautions for synthesis\n"
        "Concrete limitations/outliers only.\n\n"
        "Packet follows:\n\n"
        f"{packet}"
    )


def process(meta: dict, force: bool) -> dict:
    outpath = ROOT / meta["aggregate"]
    packet_path = ROOT / meta["packet"]
    if outpath.exists() and not force:
        return {"cell": meta["cell"], "status": "skipped"}
    packet = packet_path.read_text(errors="ignore")
    txt, usage = api_call(build_prompt(packet))
    outpath.write_text(txt.rstrip() + "\n")
    return {"cell": meta["cell"], "status": "ok", "usage": usage}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--missing-only", action="store_true", default=True)
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--concurrency", type=int, default=CONCURRENCY)
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    manifest = json.loads((AGG / "manifest.json").read_text())
    items = []
    for meta in manifest:
        outpath = ROOT / meta["aggregate"]
        if args.force or not outpath.exists():
            items.append(meta)
    if args.limit:
        items = items[: args.limit]
    print(json.dumps({"model": MODEL, "items": len(items), "concurrency": args.concurrency}), flush=True)
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as ex:
        futs = {ex.submit(process, meta, args.force): meta["cell"] for meta in items}
        for fut in concurrent.futures.as_completed(futs):
            try:
                res = fut.result()
            except Exception as e:
                res = {"cell": futs[fut], "status": "error", "error": repr(e)}
            results.append(res)
            print(json.dumps(res, ensure_ascii=False), flush=True)
    bad = [r for r in results if r["status"] == "error"]
    if bad:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
